### ISSUE TITLE
兄弟你好

### ISSUE THREAD

**Issue by lucy124** [dzghxs/XposedRedDevil#1]
请把fork我的zcc124这个仓库删除了吧！谢谢合作

**Comment by dzghxs** [comment]
我没有fork你的库呀，我看了我这边没有记录呀

**Comment by lucy124** [comment]
> 我没有叉你的库呀，我看了我这边没有记录呀

但是我看你的有啊
![qq 20190117093405](https://user-images.githubusercontent.com/26277127/51289423-1806c400-1a3b-11e9-8321-f4701590e686.png)

**Comment by lucy124** [comment]
> 我没有叉你的库呀，我看了我这边没有记录呀

你加我的微信号兄弟：15371013862
