### ISSUE TITLE
怎么编译打成apk

### ISSUE THREAD

**Issue by HHjoke** [dzghxs/XposedRedDevil#20]
能讲一下怎么编译打成apk吗谢谢，我b站上搜在github打包apk出错

**Comment by dzghxs** [comment]
> 能讲一下怎么编译打成apk吗谢谢，我b站上搜在github打包apk出错

电脑安装Android开发环境，包括sdk，编译器（Android studio），git，下载项目到本地，编译运行

**Comment by qqqwen080508** [comment]
大佬，我第一次用github
，不知道该怎么在手机端上运行这个AP k，能不能教一下我，谢谢^ω^
