### ISSUE TITLE
编译最新版本无法适用于8.0.46版本的微信

### ISSUE THREAD

**Issue by haishen668** [dzghxs/XposedRedDevil#22]
我按照网上的教程编译了app，并且使用magisk安装了lsposed框架 并且启用了模块
但是软件没有作用

**Comment by dzghxs** [comment]
加我，我看看
![1706522075358](https://github.com/dzghxs/XposedRedDevil/assets/16187345/a952f370-fd15-4c37-a7bc-f8ad57857827)
