### ISSUE TITLE
乐视 Pro 2 测试没反应

### ISSUE THREAD

**Issue by SmallRedSister** [dzghxs/XposedRedDevil#7]
软件开启之后，有什么要求吗？群聊要关闭消息免打扰吗？或者其他的

**Comment by dzghxs** [comment]
手机版本号，root还是免root请告诉我

**Comment by SmallRedSister** [comment]
第一次没有成功，打开关闭又重启三次以后可以了，微信当前聊天界面可以抢红包（自己发的或者别人发的），其他的没测试出来，不知道还没有其他功能

**Comment by dzghxs** [comment]
可能是刚开始没获取到微信版本，所以就会无效，之后获取到了就可以了
